/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  javascriptSidebar: [{ type: 'autogenerated', dirName: 'JavaScript' }],
  nodejsSidebar: [{ type: 'autogenerated', dirName: 'NodeJS' }],
	es6Sidebar: [{ type: 'autogenerated', dirName: 'es6' }],
	cssSidebar: [{ type: 'autogenerated', dirName: 'css' }],
  vimSidebar: [{ type: 'autogenerated', dirName: 'vim' }],
	nginxSidebar: [{ type: 'autogenerated', dirName: 'nginx' }],
  reactSidebar: [{ type: 'autogenerated', dirName: 'React' }],
  gitSidebar: [{ type: 'autogenerated', dirName: 'git' }],
  charlesSidebar: [{ type: 'autogenerated', dirName: 'charles' }],
	httpSidebar: [{ type: 'autogenerated', dirName: 'http' }],
	vueSidebar: [{ type: 'autogenerated', dirName: 'vue' }],
	vue3Sidebar: [{ type: 'autogenerated', dirName: 'vue3' }],
	webpackSidebar: [{ type: 'autogenerated', dirName: 'webpack' }],
	algorithmSidebar: [{ type: 'autogenerated', dirName: 'algorithm' }],
};

module.exports = sidebars;
