/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: 'JavaScript',
      items: [
				'JavaScript/this'
      ],
    },
  ],
	gitSidebar: [
		{
			type: 'category',
			label: 'Git',
			items: [
				'git/git',
				'git/conflict',
				'git/fork-clone-branch',
				'git/git-stash',
				'git/git-pull-git-fetch',
				'git/git-rebase-git-merge',
				'git/git-reset-git-revert',
				'git/git-stash',
				'git/HEAD-tree-index',
				'git/Version-control',
			]
		},
	],
	vimSidebar: [
		'vim/vi与vim',
		'vim/vim命令速查',
		'vim/VIM工作模式',
		'vim/简明Vim练级攻略'
	]
};

module.exports = sidebars;
